### ISSUE TITLE
UserId is a string

### ISSUE THREAD

**Issue by martinmasse** [tarr11/IntercomDotnet#15]
Hi,

public dynamic Get(string email = null, int? userId = null)

userId is a string, not an int.

**Comment by mgoodfellow** [comment]
Yeah, that is a good spot, I think that has been a bug since the beginning. It has never affected me as my user_id's are defined by my integrations as integers.

Did you want to open a PR to change this? I'm happy to merge.

I might be able to find the time to go through and change it later this week if not.

Thanks for the report!
