### ISSUE TITLE
Problem with createdAt DateTime for Events

### ISSUE THREAD

**Issue by jooooel** [tarr11/IntercomDotnet#8]
Not sure if I have missed something but trying to send an event like this

``` C#
client.Events.Post(eventName, DateTime.UtcNow, userId, metadata);
```

leads to a 400 from Intercom. The generated Unix timestamp contains a dot, since the calculated value of TotalSeconds in `Client.GetUnixTimestamp()` is a double. So this led me to truncate the Milliseconds from the DateTime using an extension method:

``` C#
client.Events.Post(eventName, DateTime.UtcNow.Truncate(TimeSpan.TicksPerSecond), userId, metadata);
```

Intercom now accepts the Event, but the Unix timestamp is an hour off. I think the problem lies in 

``` C#
new DateTime(1970, 1, 1).ToUniversalTime() // 1969-12-31 23:00:00
```

in `Client.GetUnixTimestamp()`. It should just be

``` C#
return (inputTime - new DateTime(1970, 1, 1)).TotalSeconds;
```

**Comment by mgoodfellow** [comment]
Hi @jooooel,

Time zones are always a pain - I think I would have implemented this when I was in the UTC/GMT timezone so never picked this up.

I believe you are right in your assertion, this is because the `inputTime` will localised to your local timezone, but then I use a UTC version of 01/01/1970.

I think your fix is fine as it will be working out the difference for your timezone, it is equivilent to (what would have also been correct, but more long-winded!)

``` csharp
return (inputTime.ToUniversalTime() - new DateTime(1970,1, 1).ToUniversalTime()).TotalSeconds;
```

Thanks for finding this, really appreciated.

Can you open a PR for this? If not I can look at patching it in the next couple of days.

Kind regards,

Mike

**Comment by jooooel** [comment]
Hi @mgoodfellow!
I have created a [PR](https://github.com/tarr11/IntercomDotnet/pull/9) with a solution I think is good. Have a look!

By the way, thanks for the lib. Nice work! :)

**Comment by mgoodfellow** [comment]
Thanks for the PR - this is now merged.

I will close this issue when I release a patched package to NuGet (hopefully this evening, but it might be in the next couple of days).

**Comment by jooooel** [comment]
Have you had the time to release a new NuGet package @mgoodfellow ?

**Comment by mgoodfellow** [comment]
Cheers for the reminder - this has been published now!
